name: Java Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: HexedPlugin_pub.jar
        path: build/libs/*.jar

    - name: Create Release
      if: strategy.job-index == 0
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Hex plugin Build ${{ github.run_number }}
          draft: false
          prerelease: false
    - name: Create Release2
    # You may pin to the exact commit or the version.
  # uses: ncipollo/release-action@4b71ee3b25951e6098e7434cdc485edc5b3adab2
      uses: ncipollo/release-action@v1.7.3
      with:
        # An optional flag which indicates if we should update a release if it already exists. Defaults to false.
        #allowUpdates: # optional, default is 
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifact: build/libs/*.jar # optional, default is     
        # Optionally marks this release as a draft release. Set to true to enable.
        draft: false # optional, default is   
        token: ${{ secrets.GITHUB_TOKEN }}
